const productImages = (prefix, count, labels = []) =>
  Array.from({ length: count }, (_, index) => ({
    label: labels[index] ?? `产品图 ${index + 1}`,
    src: `/assets/products/${prefix}-${String(index + 1).padStart(2, "0")}.jpg`,
  }));

const leisureSpecs = (overrides = {}) => {
  const base = {
    电压: "60/72V 通用",
    控制器: "18管60/72V 通用",
    减震: "舒适液压",
    轮距: "795mm",
    电机: "800W 40H",
    轮胎: "前后300-10",
    速度: "28km/h",
    轴距: "1590mm",
    仪表: "LED液晶仪表",
    大灯: "LED大灯",
    重量: "155Kg",
    尺寸: "2160*930*1690mm",
    ...overrides,
  };
  return Object.entries(base);
};

const vehicleSpecs = {
  tiger: {
    电压: "72V",
    控制器: "72V 24管控制器",
    减震: "舒适液压",
    轮距: "910mm",
    电机: "1000W差速电机",
    轮胎: "3.00-10真空胎",
    速度: "28km/h",
    轴距: "2170mm",
    仪表: "LED液晶仪表",
    大灯: "LED大灯",
    重量: "180kg额定载重",
    尺寸: "2170*910*1650mm",
  },
  q7: {
    电压: "72V",
    控制器: "72V 30管控制器",
    减震: "加强舒适液压",
    轮距: "930mm",
    电机: "1200W加强差速电机",
    轮胎: "3.50-10加厚真空胎",
    速度: "28km/h",
    轴距: "2250mm",
    仪表: "LED液晶仪表",
    大灯: "LED大灯",
    重量: "220kg额定载重",
    尺寸: "2250*930*1680mm",
  },
  a8: {
    电压: "60V",
    控制器: "60V 18管静音控制器",
    减震: "舒适液压",
    轮距: "880mm",
    电机: "800W静音差速电机",
    轮胎: "3.00-10真空胎",
    速度: "28km/h",
    轴距: "2120mm",
    仪表: "LED液晶仪表",
    大灯: "LED大灯",
    重量: "160kg额定载重",
    尺寸: "2120*880*1600mm",
  },
  t5: {
    电压: "60V",
    控制器: "60V 15管控制器",
    减震: "舒适液压",
    轮距: "850mm",
    电机: "650W轮毂电机",
    轮胎: "3.00-8真空胎",
    速度: "28km/h",
    轴距: "2050mm",
    仪表: "LED液晶仪表",
    大灯: "LED大灯",
    重量: "150kg额定载重",
    尺寸: "2050*850*1180mm",
  },
  k3: {
    电压: "48V",
    控制器: "48V 12管控制器",
    减震: "舒适液压",
    轮距: "760mm",
    电机: "500W基础轮毂电机",
    轮胎: "2.75-8真空胎",
    速度: "25km/h",
    轴距: "1800mm",
    仪表: "LED液晶仪表",
    大灯: "LED大灯",
    重量: "120kg额定载重",
    尺寸: "1800*760*1120mm",
  },
};

const modelSpecs = (id) => Object.entries(vehicleSpecs[id]);

export const defaultCatalog = {
  updatedAt: new Date().toISOString(),
  vehicles: [
    {
      id: "tiger",
      name: "星瑞Plus",
      series: "休闲篷车",
      tags: ["热销款", "新品"],
      status: "已发布",
      color: "#b73a3a",
      price: "¥6,999",
      slogan: "热销稳定 | 72V长续航 | 1000W差速电机 | 家庭代步",
      specs: modelSpecs("tiger"),
      inventory: 168,
      dealerPolicy: "门店标价6999元，建议成交价6599元，适合作为热销主推款。",
      images: productImages("xingrui", 8, ["整车侧面", "侧面展示", "前侧视角", "座椅细节", "正面展示", "前脸细节", "前轮细节", "中控细节"]),
    },
    {
      id: "q7",
      name: "陆尚",
      series: "休闲篷车",
      tags: ["耐用款"],
      status: "已发布",
      color: "#8a72cc",
      price: "¥7,599",
      slogan: "耐用稳定 | 72V高功率 | 1200W加强差速 | 乡镇高频使用",
      specs: modelSpecs("q7"),
      inventory: 94,
      dealerPolicy: "门店标价7599元，建议成交价7199元，乡镇道路和高频使用优先推荐。",
      images: productImages("lushang", 8, ["整车侧面", "右侧展示", "前侧展示", "后侧展示", "车身侧面", "轮胎细节", "中控细节", "驾驶舱"]),
    },
    {
      id: "a8",
      name: "CL9",
      series: "轻奢篷车",
      tags: ["利润款"],
      status: "已发布",
      color: "#d8c7a6",
      price: "¥7,999",
      slogan: "轻奢外观 | 60V静音差速 | 舒适座舱 | 门店利润款",
      specs: modelSpecs("a8"),
      inventory: 52,
      dealerPolicy: "门店标价7999元，建议成交价7599元，主打外观质感和舒适配置。",
      images: productImages("cl9", 8, ["海报主图", "整车侧面", "后视图", "把手细节", "座椅扶手", "充电口", "前轮细节", "储物格"]),
    },
    {
      id: "t5",
      name: "H6",
      series: "休闲系列",
      tags: ["舒适款"],
      status: "已发布",
      color: "#b8d7da",
      price: "¥5,299",
      slogan: "舒适上下车 | 60V轮毂电机 | 老人代步 | 社区短途",
      specs: modelSpecs("t5"),
      inventory: 213,
      dealerPolicy: "门店标价5299元，建议成交价4999元，适合老人代步和社区短途。",
      images: productImages("h6", 8, ["整车侧面", "后侧视角", "正面展示", "前侧视角", "双座展示", "海报主图", "米色款", "红色款"]),
    },
    {
      id: "k3",
      name: "乐萌",
      series: "休闲系列",
      tags: ["活动款"],
      status: "已发布",
      color: "#f5a9be",
      price: "¥4,599",
      slogan: "活动引流 | 48V基础代步 | 多彩小车 | 价格敏感客户",
      specs: modelSpecs("k3"),
      inventory: 87,
      dealerPolicy: "门店标价4599元，活动建议价3999元，经销商结算参考价3180元，适合作为活动引流款。",
      images: productImages("lemeng", 6, ["粉色款", "红色款", "紫色款", "金色款", "绿色款", "海报主图"]),
    },
  ],
};
